### ISSUE TITLE
Permission comparison not working properly

### ISSUE THREAD

**Issue by matiasgarcia91** [brainhubeu/react-permissible#3]
Hi! I was just trying this out and got stuck with an issue. 
I think there is something wrong when comparing userPermissions and requiredPermissions, for example in my case:

`<PermissibleRender userPermissions={['UnlockLogin', 'aaaa', 'bb']} requiredPermissions={['UnlockLogin', 'aaaa']} >` This works properly.

But if you change the order of the userPermissions by putting the not-required permission at the beginning for example
`<PermissibleRender userPermissions={[ 'bb', 'UnlockLogin', 'aaaa']} requiredPermissions={['UnlockLogin', 'aaaa']} >` now this wont render the component. 

I don't think I'm doing anything wrong but maybe you can spot it

**Comment by matiasgarcia91** [comment]
I fixed it removing is-subset and using lodash to compare, specifically changed 
`return isSubset(userPermissions, requiredPermissions);`
to this: 
`import difference from 'lodash/difference';
difference(requiredPermissions, userPermissions).length === 0;
`

**Comment by piotr-s-brainhub** [comment]
@matiasgarcia91 you're welcome to open a PR

**Comment by matiasgarcia91** [comment]
I tried pushing a branch but it was rejected by permissions stuff, I'll gladly do a PR 😄

**Comment by piotr-s-brainhub** [comment]
PRs should be opened from forks

**Comment by matiasgarcia91** [comment]
thanks, I'll have that up in the afternoon. great tool!

**Comment by matiasgarcia91** [comment]
@piotr-s-brainhub https://github.com/brainhubeu/react-permissible/pull/4

**Comment by adam-golab** [comment]
I've merged your PR #4. Thanks for contributing 🙂
