### ISSUE TITLE
Default Mask option

### ISSUE THREAD

**Issue by praveenkutty** [brainhubeu/react-permissible#32]
Hi, 

I wanted to know if you have a option to mask a component instead of hiding it when permissions does not satisfy. 

I would need this since I want the user to see the particular component / element / button but cannot do any operation associated to it, and also would like to show an alert that they need to contact admin for required permissions.

In short similar to renderOtherwise is there renderMasked?.

**Comment by kkoscielniak** [comment]
Hi @praveenkutty, 

I apologize for responding so late. Basically, there's no such functionality implemented. But you can create two components (one would be "masked"). Or to make it more reusable render the same component twice (with and without the `masked` prop). 

Best, 
Krystian
