### ISSUE TITLE
Unnecessary devDependencies and examples

### ISSUE THREAD

**Issue by kjendrzyca** [brainhubeu/react-permissible#6]
The package includes dependencies that are not or shouldn't be used like `redux` or `react-router`. Also, the examples folder could be removed. Probably some other files like `docker-compose.yml` are just noise that affect package size.

**Comment by kkoscielniak** [comment]
I will check what packages are not necessary and remove the noise. Thanks for the input @kjendrzyca.

**Comment by kkoscielniak** [comment]
@kjendrzyca There's a pull request #13 cleaning up the repository, if you'd like to take a look
